### ISSUE TITLE
A few suggestions about left sidebar interaction

### ISSUE THREAD

**Issue by Runjuu** [cp3hnu/Starry#2]
<img width="223" alt="screen shot 2017-11-06 at 12 23 13 pm" src="https://user-images.githubusercontent.com/12002941/32425378-a0509378-c2ed-11e7-8d86-32ee2bdd5d8d.png">

I think that the fixed interaction of left sidebar is better than the scrollable one, and it doesn't seem like that user can adjust the width of the left sidebar yet.

**Comment by cp3hnu** [comment]
It should not scroll horizontally. Can you tell me the version of your macOS?

**Comment by Runjuu** [comment]
Sure, here you are
<img width="698" alt="screen shot 2017-11-06 at 10 06 32 pm" src="https://user-images.githubusercontent.com/12002941/32445062-94662724-c33f-11e7-840d-05e33fb8d685.png">

**Comment by cp3hnu** [comment]
Thank you for your reply. This should be a bug and I'll fix in the next version.

**Comment by cp3hnu** [comment]
V1.0.7 is available on Mac App Store. Please let me know if it solves this problem.

**Comment by Runjuu** [comment]
@cp3hnu The problem has been solved. 👏
