### ISSUE TITLE
GitHub API rate limit exceeded

### ISSUE THREAD

**Issue by NsLib** [cp3hnu/Starry#3]
![rate-limit](https://user-images.githubusercontent.com/2672226/32555339-0bf4bd50-c462-11e7-995d-f46b9a2dc7de.png)

![log](https://user-images.githubusercontent.com/2672226/32555409-45a2042c-c462-11e7-9fb6-2854257ae372.png)

PS: Already logged in

**Comment by cp3hnu** [comment]
Thank you for posting the issue. Is there a error in reading repository? I fixed it and submitted a new version to apple to review.

**Comment by cp3hnu** [comment]
V1.0.7 is available on Mac App Store. It fixed this bug.
