### ISSUE TITLE
如果不再维护, 求开源😜😜

### ISSUE THREAD

**Issue by vlaw** [cp3hnu/Starry#8]

**Comment by cp3hnu** [comment]
已经开源了。但是需要自己做这两件事
First, create your app on GitHub and get the Client ID and Client Secret, then fill the clientID and clientSecret in Shared/Constant.swift
Second, set up Realm Object Server, then fill the realmSyncHost in Shared/Constant.swift.

**Comment by gatspy** [comment]
这个是我最喜欢的github mac 客户端了. 
build mac版本的时候要怎么去掉`In-App Purchase` 错误呢?
